defaults: &defaults
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  region: <%=ENV["AWS_REGION"]%>
development:
  <<: *defaults
  bucket: "dealer-development"
test:
  <<: *defaults
  bucket: "dealer-test"
production:
  <<: *defaults
  bucket: "dealer-production"